### ISSUE TITLE
Support prefix in CSS variables?

### ISSUE THREAD

**Issue by mryechkin** [nado1001/style-dictionary-tailwindcss-transformer#326]
First off, thank you for this awesome library!

I'm using the `prefix` option in Style Dictionary, so that my generated CSS variables look something like this (`acme` is the prefix here):

```css
:root {
  --acme-color-rose: #e11d48;
  --acme-color-violet: #7c3aed;
  --acme-color-secondary: var(--acme-color-rose);
  --acme-color-primary: var(--acme-color-violet);
}
```

However, when setting `isVariables` to `true`, the prefix doesn't seem to be taken into account, as the output contains variables without it:

```js
theme: {
  extend: {
    color: {
      violet: "var(--color-violet)",
      rose: "var(--color-rose)",
      primary: "var(--color-primary)",
      secondary: "var(--color-secondary)"
    }
  },
}
```

Is this something that can be supported? Or is there a way to specify that already?
